# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: mkdocs.yml
    -   id: check-added-large-files
        args: ['--maxkb=1500']
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: .*\.ipynb$
    -   id: check-case-conflict
    -   id: name-tests-test
        args: [--pytest-test-first]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
    -   id: gitleaks

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
        # Run the linter.
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
    -   id: pycln
        args: [--all]

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
    -   id: clang-format
        types_or: [c, c++, cuda]