# default config can be found https://docs.astral.sh/ruff/configuration/

required-version = ">=0.13.0"

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "docs",
  "node_modules",
  "site-packages",
  ".venv",
  "*egg-info",
]

line-length = 88
indent-width = 4
# target-version = "py312"  # Uncomment and set the target Python version if needed

[lint]
select = [ # https://docs.astral.sh/ruff/rules/
  "C",   # Complexity
  "D",   # PyDocStyle
  "E",   # PyCodeStyle Errors
  "F",   # PyFlakes
  "W",   # PyCodeStyle Warnings
  "ANN", # flake8-annotations
  "B",   # flake8-bugbear
  "TC",  # flake8-type-checking
  "PTH", # flake8-use-pathlib
  "NPY", # NumPy specific rules
  "TID", # flake8-tidy-imports
  "SIM", # flake8-simplify
  "I",   # isort
  "PL",  # PyLint
  "ERA", # eradicate
]
ignore = [
  "D105",    # undocumented magic method
  "PLC0415", # import at top of file
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
preview = true

[lint.per-file-ignores]
"test_*.py" = [
  "ANN201",  # Ignore annotation requirements in tests
  "PLR2004", # Ignore magic numbers in tests
  "PLR6301", # Method could be a function, class method, or static method
]
"*.ipynb" = [
  "I",       # Ignore import-related errors in notebooks
  "PLR2004", # Ignore magic numbers in notebooks
]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
